# Generated by Django 5.1.15 on 2026-10-01 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('head_seq', models.BigIntegerField(default=0, help_text='Monotonically increasing sequence number of the latest operation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('rewrite', 'Rewrite'), ('grammar', 'Grammar & Fix'), ('shorten', 'Shorten'), ('continue', 'Continue Writing'), ('summary', 'Summary of Missed Edits'), ('suggest', 'Suggestion'), ('ask', 'Ask Document')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('anchor_start', models.CharField(blank=True, help_text='Starting CharId', max_length=128, null=True)),
                ('anchor_end', models.CharField(blank=True, help_text='Ending CharId', max_length=128, null=True)),
                ('instruction', models.TextField(blank=True, default='')),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_start', models.CharField(max_length=128)),
                ('anchor_end', models.CharField(max_length=128)),
                ('proposed_text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='documents.aijob')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='documents.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'user'], name='documents_c_documen_6a60a3_idx')],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_seq', models.BigIntegerField(help_text='Globally ordered sequence number within this document.')),
                ('op_id', models.CharField(db_index=True, help_text='Globally unique idempotency key.', max_length=128, unique=True)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('lamport', models.BigIntegerField()),
                ('type', models.CharField(choices=[('insert', 'Insert'), ('delete', 'Delete')], max_length=16)),
                ('payload', models.JSONField(help_text='Full serialized Op dictionary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['server_seq'],
                'indexes': [models.Index(fields=['document', 'server_seq'], name='documents_o_documen_a67a6b_idx'), models.Index(fields=['document', 'created_at'], name='documents_o_documen_632011_idx')],
                'unique_together': {('document', 'server_seq')},
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_seq', models.BigIntegerField(help_text='Sequence number up to which state is captured.')),
                ('state', models.JSONField(help_text='Full serialized RGA document state.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='documents.document')),
            ],
            options={
                'ordering': ['-server_seq'],
                'indexes': [models.Index(fields=['document', '-server_seq'], name='documents_s_documen_cc149a_idx')],
            },
        ),
    ]
