# Generated by Django 5.1.15 on 2026-10-02 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gc_seq',
            field=models.BigIntegerField(default=0, help_text='Tombstones deleted at or before this seq may have been garbage-collected. Ops based on an older state are rejected as stale.'),
        ),
        migrations.CreateModel(
            name='SiteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=64)),
                ('acked_seq', models.BigIntegerField(blank=True, null=True)),
                ('retired', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'last_seen'], name='documents_s_documen_46ada5_idx')],
                'unique_together': {('document', 'site_id')},
            },
        ),
    ]
